### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by appleimperio** [dhayab/homebridge-withings-air-quality#16]
Was working ok and now..

(node:1556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at r.getTemperature (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:4:2582)
    at i.updateTemperature (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:5207)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:3615
    at i.<anonymous> (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:4575)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:1529
    at Object.next (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:1634)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:547
    at new Promise (<anonymous>)
    at t (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:295)
    at CurrentTemperature.<anonymous> (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:4505)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at r.getCarbonDioxide (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:4:2513)
    at i.updateAirQuality (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:4891)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:3409
    at i.<anonymous> (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:4575)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:1529
    at Object.next (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:1634)
    at /homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:547
    at new Promise (<anonymous>)
    at t (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:295)
    at AirQuality.<anonymous> (/homebridge/node_modules/homebridge-withings-air-quality/dist/index.js:6:4505)

**Comment by martindinicolino** [comment]
same here...
were you able to find a fix? is anybody able to help?

**Comment by appleimperio** [comment]
I just remove it wait a few days and add it again and it worked. Looks like too many attempts to contact Withings lock the plugin.

**Comment by martindinicolino** [comment]
I see, thank you for your reply.

But have you had to remove it and wait periodically? Or is it just working now?

**Comment by appleimperio** [comment]
Its working now only happened if I had other plugin that keep reloading the homebridge goes down again

**Comment by martindinicolino** [comment]
Thank you, i’ll give it a try. That might possibly the solution for most of us here...

**Comment by appleimperio** [comment]
Just to let you know the problem start again but this time the solution is not working. I hope we found one!

**Comment by martindinicolino** [comment]
too bad, thank you anyways

**Comment by dhayab** [comment]
Hi, I released a fix for this plugin to update the URL used to connect to Withings, it might solve your issue. If you're using a recent version of Homebridge this plugin might display warnings, but it should work nonetheless (see #24).

**Comment by choicedraught** [comment]
Thank you very much.
