### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by koupus** [dhayab/homebridge-withings-air-quality#25]
Hello,

First thanks for your work. 

I've this in the homebridge logs :
[homebridge-withings-air-quality] This plugin slows down Homebridge. The read handler for the characteristic 'Carbon Dioxide Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

and: 
[homebridge-withings-air-quality] This plugin generated a warning from the characteristic 'Carbon Dioxide Level': Characteristic not in required or optional characteristic section for service AirQualitySensor. Adding anyway.. See https://git.io/JtMGR for more info.
(node:60969) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: iid cannot be undefined for characteristic 'Carbon Dioxide Level'
    at CarbonDioxideLevel.Characteristic.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2156:11)
    at CarbonDioxideLevel.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2130:25)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at CarbonDioxideLevel.Characteristic.toHAP (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1293:38)
    at _loop_1 (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:617:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:454:21
(node:60969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:60969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you something ?

Thanks, bye.

Tom

**Comment by IgorZigon** [comment]
I have the same problem, any suggestion?
