### ISSUE TITLE
Error in log and no values anymore

### ISSUE THREAD

**Issue by tooh** [dhayab/homebridge-withings-air-quality#3]
Working OK for a while and now for some days this issue.

``
(node:7823) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at r.getTemperature (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:4:2582)
    at i.updateTemperature (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:5039)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:3596
    at i.<anonymous> (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4407)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:1529
    at Object.next (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:1634)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:547
    at new Promise (<anonymous>)
    at t (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:295)
    at Characteristic.CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4337)
    at Characteristic.CurrentTemperature.emit (events.js:321:20)
    at Characteristic.CurrentTemperature.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:321:20)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:321:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7823) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at r.getCarbonDioxide (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:4:2513)
    at i.updateAirQuality (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4723)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:3390
    at i.<anonymous> (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4407)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:1529
    at Object.next (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:1634)
    at /usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:547
    at new Promise (<anonymous>)
    at t (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:295)
    at Characteristic.AirQuality.<anonymous> (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4337)
    at Characteristic.AirQuality.emit (events.js:321:20)
    at Characteristic.AirQuality.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:321:20)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:321:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
``

**Comment by dhayab** [comment]
Thank you for noticing, apparently the Withings login page now requires additional data. An update with the fix should be available in a few hours.

**Comment by tooh** [comment]
Just installed update. Get readings again.

Thx for quick response.
