### ISSUE TITLE
Can't start anymore

### ISSUE THREAD

**Issue by hmoreau94** [dhayab/homebridge-withings-air-quality#5]
Hi, 

First of all thanks for trying to bring withing scale sensors to Homebridge. Nevertheless, their seem to be an issue, upon installation and after configuration, homebridge will loop on restart displaying the following error. 

`TypeError: Cannot read property 'replace' of undefined
    at i.get [as formattedMacAddress] (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:4217)
    at new i (/usr/local/lib/node_modules/homebridge-withings-air-quality/dist/index.js:6:2560)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by dhayab** [comment]
Hi @hmoreau94, it most probably occurs because there is no mac address set in your configuration.

A valid configuration looks like that:

```json
{
  "accessory": "Withings Air Quality",
  "name": "Bathroom scale",
  "email": "my.withings@email.com",
  "password": "myWithingsPassword",
  "mac": "0a:b2:c3:d4:e5:f6",
  "levels": [350, 1000, 2500, 5000]
}
```

You can get your Withings scale MAC address in the batteries compartment.
